modular-rocks/slimfast-turbo

config/eslint-config/.eslintrc.cjs, packages/workspace/src/index.ts, packages/workspace/src/types.ts, packages/workspace/src/workspace/codebase/copy/index.test.ts, packages/workspace/src/workspace/codebase/copy/index.ts, packages/workspace/src/workspace/codebase/file/index.test.ts, packages/workspace/src/workspace/codebase/file/index.ts, packages/workspace/src/workspace/codebase/index.test.ts, packages/workspace/src/workspace/codebase/index.ts, packages/workspace/src/workspace/codebase/make-directory/index.test.ts, packages/workspace/src/workspace/codebase/make-directory/index.ts, packages/workspace/src/workspace/codebase/save/index.ts, packages/workspace/src/workspace/codebase/store-dependencies/index.test.ts, packages/workspace/src/workspace/codebase/store-dependencies/index.ts, packages/workspace/src/workspace/index.test.ts, packages/workspace/src/workspace/index.ts, packages/workspace/src/workspace/pipeline/index.test.ts, packages/workspace/src/workspace/pipeline/index.ts
We're migrating from default exports to named exports in the `workspace` package with this PR.
=> [workspace] Use named exports

.changeset/shy-seals-relate.md, packages/workspace-node/src/index.ts, packages/workspace-node/src/workspace/codebase/file/index.test.ts, packages/workspace-node/src/workspace/codebase/file/index.ts, packages/workspace-node/src/workspace/codebase/file/parse/index.ts, packages/workspace-node/src/workspace/codebase/file/print/index.ts, packages/workspace-node/src/workspace/codebase/file/too-simple/index.ts, packages/workspace-node/src/workspace/codebase/index.test.ts, packages/workspace-node/src/workspace/codebase/index.ts, packages/workspace-node/src/workspace/index.test.ts, packages/workspace-node/src/workspace/index.ts
Continuing the migration started in #29 for the `workspace-node` package.
=> [workspace-node]: Use named exports

.changeset/ninety-dolls-leave.md, packages/workspace-node/src/workspace/codebase/file/index.test.ts, packages/workspace-node/src/workspace/codebase/file/index.ts
Now we will detect the predominant end-of-line (EOL) format in the code and preserve this EOL when generating code from an AST.
Progressing with issue #4.
=> [workspace-node]: Preserve end of lines

.changeset/dry-fireants-stare.md, .github/workflows/ci.yml, packages/slimfast-node/src/slimfast/pipeline/build/builder/combine-imports/index.ts, packages/slimfast-node/src/slimfast/pipeline/build/builder/import-statement/index.ts, packages/slimfast-node/src/slimfast/pipeline/build/builder/index.ts
This PR normalizes the output of import paths in the `slimfast-node` package to use POSIX-style forward slashes.
Before (on windows)
```
import { foo } from 'path\\to\\lib';
```
After (on windows)
```
import { foo } from 'path/to/lib';
```
Closes #4
=> [slimfast-node]: use posix paths for imports

config/eslint-config/.eslintrc.cjs, packages/workspace/src/types.ts, packages/workspace/src/workspace/codebase/copy/index.ts, packages/workspace/src/workspace/codebase/file/index.ts, packages/workspace/src/workspace/codebase/index.ts, packages/workspace/src/workspace/codebase/make-directory/index.ts, packages/workspace/src/workspace/codebase/save/index.ts, packages/workspace/src/workspace/codebase/store-dependencies/index.ts, packages/workspace/src/workspace/index.ts, packages/workspace/src/workspace/pipeline/index.ts
This PR introduces JSDoc-style documentation for each function, method, and property. This enhances maintainability and readability, providing clear insight into what each function does, its parameters, and expected return values. We could also use this to automatically generate documentation later on.
=> [workspace]: Add jsdocs

.github/workflows/ci.yml, package.json
In the current setup, we execute the build process twice. With this change, the build will only run once. Following the build, tests will be executed without triggering another build.
=> [CI]: Run build only once

config/eslint-config/.eslintrc.cjs, package.json, pnpm-lock.yaml
The unused devDependency `babel-jest` has been removed.
=> Remove unused devDependency `babel-jest`

packages/workspace/src/workspace/codebase/copy/index.test.ts
In this PR, additional tests have been added for the `copy` utility within the `workspace` package to ensure its functionality.
=> [workspace]: Add tests for `copy` utility

.changeset/three-spiders-shave.md, packages/workspace/src/workspace/pipeline/index.test.ts, packages/workspace/src/workspace/pipeline/index.ts
In this PR, the `pipeline` function utility in the `workspace` package has been updated to correctly reject errors in a promise. Additionally, tests have been added to ensure its functionality.
=> [workspace]: Fix pipeline promise error handling and add tests

.changeset/cold-shrimps-dream.md, packages/workspace/src/workspace/codebase/index.test.ts, packages/workspace/src/workspace/codebase/index.ts
In this PR, the `save` method of the `Codebase` class in the `workspace` package has been updated to return a promise, enabling its use with `await` for better asynchronous handling.
Numerous tests have been added for the `Codebase` class.
=> [workspace]: Make Codebase `save` method return a promise. Add tests for Codebase

.changeset/slimy-paws-sparkle.md, packages/workspace-node/src/workspace/codebase/file/index.test.ts, packages/workspace-node/src/workspace/codebase/file/index.ts
- Tests have been added for the `FileContainer`.
- A minor fix has been made to the `addImport` method's return.
=> [workspace-node]: Add tests for `FileContainer` and fix to the `addImport` method's return

packages/traverse-files/src/tests/convenience.test.ts, packages/traverse-files/src/tests/index.test.ts
Refactor tests for the `traverse-files` package to also be executable from the root of the monorepo. This is necessary for testing the monorepo's coverage.
=> [traverse-files]: Refactor tests for monorepo root execution

.devcontainer/devcontainer.json
Changes the Node.js & TypeScript image version in `.devcontainer/devcontainer.json` to `1-16-bullseye` (Node v16) to align more closely with our minimum Node.js requirement.
=> [devcontainer]: Change Node image to v16

.changeset/forty-fishes-protect.md, packages/slimfast/src/index.test.ts
Adds a test for the `save` method in the `slimfast` package. It makes sure that it correctly invokes the `save` method of its `refactored` property.
=> [slimfast]: Add test for `save` method

.changeset/tough-forks-shake.md, .devcontainer/devcontainer.json, .github/workflows/cd.yml, .github/workflows/ci.yml, package.json, packages/slimfast-node/package.json, packages/slimfast-node/tsconfig.json, packages/slimfast/package.json, packages/slimfast/tsconfig.json, packages/traverse-files/package.json, packages/workspace-node/package.json, packages/workspace-node/tsconfig.json, packages/workspace/package.json, packages/workspace/tsconfig.json
Due to the [LTS schedule of Node.js](https://nodejs.org/en/about/releases/), this PR updates the minimum required Node.js version to 18 for all packages. 
- Node.js 18 is in Active LTS status until October 2023, and Maintained until April 2025.
- This ensures that all packages stay up-to-date with the features and security updates from an actively maintained Node.js version.
=> Update min Node version to 18 for all pkgs

.changeset/brown-trainers-pump.md, packages/slimfast-node/src/slimfast/index.ts, packages/slimfast-node/src/slimfast/visitors/expression/index.ts, packages/slimfast-node/src/slimfast/visitors/utils/contraints/contains-identifiers-in-other-scopes/index.ts, packages/slimfast-node/src/slimfast/visitors/utils/contraints/has-assignment-expression/index.ts, packages/slimfast-node/src/slimfast/visitors/utils/contraints/has-blocklisted-identifiers/index.ts, packages/slimfast-node/src/slimfast/visitors/utils/contraints/has-return-statement/index.ts, packages/slimfast-node/src/slimfast/visitors/utils/contraints/has-variable-declarator/index.ts, packages/slimfast-node/src/slimfast/visitors/utils/contraints/identifiers-not-within-range/index.ts, packages/slimfast-node/src/slimfast/visitors/utils/contraints/identifiers-within-range/index.ts, packages/slimfast-node/src/slimfast/visitors/utils/contraints/is-a-function/index.ts, packages/slimfast-node/src/slimfast/visitors/utils/contraints/is-call-expression/index.ts, packages/slimfast-node/src/slimfast/visitors/utils/contraints/removes-too-much/index.ts, packages/slimfast-node/src/slimfast/visitors/utils/contraints/should-ignore/index.ts, packages/slimfast-node/src/slimfast/visitors/utils/contraints/too-small/index.ts, packages/slimfast-node/src/slimfast/visitors/utils/extract-identifiers/index.ts, packages/slimfast-node/src/slimfast/visitors/utils/not-in-extracted/index.ts, packages/slimfast-node/src/slimfast/visitors/utils/parser/index.ts, packages/slimfast-node/src/slimfast/visitors/utils/reject-parents-with-types/index.ts, packages/slimfast-node/src/slimfast/visitors/visitor/index.ts
This PR introduces JSDocs to a portion of the `slimfast-node` package.
This will be followed by another PR to complete the JSDocs documentation across the entire package.
=> [slimfast-node]: Add JSDocs

.changeset/small-bears-obey.md, packages/slimfast-node/src/slimfast/visitors/utils/contraints/is-a-function/index.test.ts, packages/slimfast-node/src/slimfast/visitors/utils/contraints/is-a-function/index.ts
This PR refactors the `isAFunction` utility function within the `slimfast-node` package. The function now directly uses `path.isFunction()`. Additionally, tests have been added.
The changes include:
- Simplified the `isAFunction` implementation by using `path.isFunction()`.
- Added tests for:
- Arrow functions
- Function declarations
- Function expressions
- Object methods
- Class methods
- Private class methods
- Non-function expressions
=> [slimfast-node]: Refactor `isAFunction` and add tests

.changeset/polite-days-hide.md, .devcontainer/devcontainer.json, .github/workflows/cd.yml, .github/workflows/ci.yml, biome.json, package.json, packages/slimfast-node/package.json, packages/slimfast-node/test-results/basic/after.ts, packages/slimfast/package.json, packages/workspace-node/package.json, pnpm-lock.yaml, turbo.json
The formatting of `packages/slimfast-node/test-results/basic/after.ts` was updated due to changes in the output formatting. This change should not affect any functionality.
=> [chore]: bump dependencies

.changeset/early-apples-sell.md, packages/slimfast-node/src/slimfast/visitors/utils/contraints/has-return-statement/index.test.ts, packages/slimfast-node/src/slimfast/visitors/utils/contraints/has-return-statement/index.ts
This PR fixes the hasReturnStatement constraint in the slimfast-node package to correctly check the parent path when traversing upwards.
=> [slimfast-node]: Fix hasReturnStatement to check path parent

.changeset/sharp-news-judge.md, packages/slimfast-node/src/slimfast/index.ts, packages/slimfast-node/src/slimfast/pipeline/extract/index.ts, packages/slimfast-node/src/slimfast/visitors/visitor/index.ts, packages/slimfast-node/src/types.ts
This PR updates the `Visitor` class in the `slimfast-node` package to be an abstract class. This change ensures that `Visitor` cannot be instantiated directly and provides a clearer structure for classes that extend `Visitor`. Additionally, it includes an abstract method that must be implemented by any subclass, further enforcing the intended use of the class hierarchy.
=> [slimfast-node]: Make Visitor an abstract class

packages/slimfast-node/src/index.test.ts, packages/workspace-node/src/index.test.ts, packages/workspace/src/index.test.ts
This PR introduces new tests designed to check if certain exports are defined, primarily to increase our code coverage.
=> [Tests]: Add export definition tests
